apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        project: zbmed
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: {{ .Values.partOfLabel }}
        app.kubernetes.io/component: backend
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - name: dataserver
          image: nginx:1.23.3
          ports:
            - containerPort: 80
          volumeMounts:
            - name: {{.Release.Name}}-data
              mountPath: "/usr/share/nginx/html"
          resources:
            requests:
              memory: 256Mi
              cpu: 0.5m
            limits:
              memory: 1Gi
      volumes:
      - name: {{.Release.Name}}-data
        persistentVolumeClaim:
          claimName: {{.Release.Name}}-pvc
