apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
        project: zbmed
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: {{ .Values.partOfLabel }}
        app.kubernetes.io/component: backend
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
        - name: web
          image: {{.Values.backend.backendImage}}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: OLS_SOLR_HOST
              value: http://{{ .Release.Name }}-solr:8983
            - name: OLS_NEO4J_HOST
              value: bolt://{{ .Release.Name }}-neo4j:7687
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: {{ .Values.backend.context }}
            - name: JDK_JAVA_OPTIONS
              value: -Xmx6G
            - name: MATOMO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: MATOMO_AUTH_TOKEN
                  name: ols4-backend-auth-token
            - name: JAVA_OPTIONS
              value: -Xmx6G
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 500Gi
