apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-solr
  labels:
    app: {{ .Release.Name }}-solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-solr
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-solr
        project: zbmed
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: {{ .Values.partOfLabel }}
        app.kubernetes.io/component: backend
        app.kubernetes.io/managed-by: Helm
    spec:
      volumes:
        - name: {{ .Release.Name }}-solr-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-solr-pvc
      securityContext:
        fsGroup: 8983
      containers:
        - name: solr
          image: {{.Values.solrImage}}
          volumeMounts:
            - mountPath: "/data"
              name: {{ .Release.Name }}-solr-storage
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Downloading data"
              rm -rf /data/solr
              mkdir /data/solr
              wget $SOLR_TARBALL_URL -O /data/tmp.tgz

              echo "Archive info"
              ls -lh /data/tmp.tgz

              echo "Testing gzip"
              if gzip -t /data/tmp.tgz; then
                echo "gzip ok, extracting as tar.gz"
                tar -zxvf /data/tmp.tgz -C /data --no-same-owner --no-overwrite-dir
              else
                echo "gzip test failed"
                exit 1
              fi

              echo "Starting solr"
              solr-foreground -a -XX:CompileCommand=exclude,com.github.benmanes.caffeine.cache.BoundedLocalCache::put
          env:
            - name: SOLR_TARBALL_URL
              value: {{.Values.solrTarballUrl}}
            - name: SOLR_HOME
              value: /data
          ports:
            - containerPort: 8983
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 16Gi
  serviceName: {{ .Release.Name }}-solr

