apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-neo4j-pvc
  labels:
    project: zbmed
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.partOfLabel }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi # 30Gi for BERD, 150Gi for HEALTH

